export const STACK_MAIN = 'STACK_MAIN';
// export const STACK_AUTH = 'STACK_AUTH';

export const SCREEN_STARTUP = 'SCREEN_STARTUP';
export const SCREEN_EXAMPLE = 'SCREEN_EXAMPLE';

export const BOTTOM_TABS = 'BOTTOM_TABS';

export const SCREEN_MY_POCKETS = 'SCREEN_MY_POCKETS';
export const SCREEN_STRATEGY = 'SCREEN_STRATEGY';
export const SCREEN_HISTORY = 'SCREEN_HISTORY';
export const SCREEN_PROFILE = 'SCREEN_PROFILE';

export const SCREEN_POCKET_DETAIL = 'SCREEN_POCKET_DETAIL';